# -*- coding: utf-8 -*-
"""Final.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FRMQASB9_FDalC-kJ-vuso4dA1UYIBTM
"""

import smtplib
import imghdr
from email.message import EmailMessage

def for_sending_images():
 msg=EmailMessage()
 msg['Subject']='How are you doing!'
 msg['From']='naturalistagnostic123@gmail.com'
 msg['To']='jyotirmaykar2000@gmail.com'
 msg.set_content('How about dinner today at 6 PM?')
 files=['Baby.jpg','mac.jpeg','tree.jpg']
 for file in files:
  with open(file, 'rb') as f:
    file_data= f.read()
    file_type= imghdr.what(f.name)
    file_name=f.name
  msg.add_attachment(file_data,maintype='image',subtype=file_type,filename=file_name)
 with smtplib.SMTP_SSL('smtp.gmail.com', 465) as smtp:
  smtp.login('naturalistagnostic123@gmail.com','Amideepbolchi123')
  smtp.send_message(msg)

def for_sending_pdf_files():
 msg=EmailMessage()
 msg['Subject']='How are you doing!'
 msg['From']='naturalistagnostic123@gmail.com'
 msg['To']='jyotirmaykar2000@gmail.com'
 msg.set_content('How about dinner today at 6 PM?')
 files=['Control lab assignment-3.pdf','55_Jyotirmay Kar_EndSem5.pdf']
 for file in files:
  with open(file, 'rb') as f:
   file_data= f.read()
   file_type= imghdr.what(f.name)
   file_name=f.name
  msg.add_attachment(file_data,maintype='application',subtype='octet-stream',filename=file_name)

 with smtplib.SMTP_SSL('smtp.gmail.com', 465) as smtp:
  smtp.login('naturalistagnostic123@gmail.com','Amideepbolchi123')
  smtp.send_message(msg)

def for_sending_html_scripts():
 msg=EmailMessage()
 msg['Subject']='How are you doing!'
 msg['From']='naturalistagnostic123@gmail.com'
 msg['To']='jyotirmaykar2000@gmail.com'
 msg.set_content('This is a plain text email')

 msg.add_alternative("""\
 <!DOCTYPE html>
 <html>
     <body>
         <h1 style="color:SlateGray;">This is an HTML Email!</h1>
     </body>
 </html>
 """, subtype='html')



 with smtplib.SMTP_SSL('smtp.gmail.com', 465) as smtp:
   smtp.login('naturalistagnostic123@gmail.com','Amideepbolchi123')
   smtp.send_message(msg)